### PR TITLE
fix update to mstatus.FS when fcsr updated : v20190830.0

### PR DESCRIPTION
**Pull request by duncangraham-Imperas**

### CODE REVIEW

**Comment by Imperas** [comment]
The ret instruction jumps to the address in the lr register. You have not set this register so it is 0. When it jumps to address 0 that is uninitialized memory, which the marning message tells you about, and then the processor takes an exception which jumps to the exception vector, which by default is at address 0, and so on.

If you put the label _exit on the ret instruction the default semihosting will intercept the execution of that instruction and terminate the simulation, e.g.:

_exit:      RET

**Comment by ShraddhaDevaiya** [comment]
Hi, Thanks for your quick response. I have tried this ```_exit : RET``` as per your inputs, but the simulation output is same as the before. Then I have just added ```_exit``` label, like this : 
```
.globl _start
.section .text
_start:           
            
init:             li x0, 0x0
		  li x5, 0x6
main:             nop
		  addi        t0, t0, 0x4
_exit:	
```
but then also it is not terminating .

**Comment by eroom1966** [comment]
Can I recommend disassembling (objdump) one of the simple provided examples 
Have a look for the exit function, and you will see the idiom used
I would also run the Same example with tracing enabled which will show The last executed instruction
Thx
Lee

**Comment by ShraddhaDevaiya** [comment]
Hi, got the solution , just we need to end the assembly program with this instructions : 
``` 
loop:
        wfi
        j loop
```
Find the reference here : https://github.com/riscv/riscv-asm-manual/blob/master/riscv-asm.md
Thanks for helping !

**Pull request merged**
